apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-dep
  labels:
    app: webserver
spec:
  replicas: 25
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: webserver
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: solutionregistry.azurecr.io/webserver:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "20Mi"
            cpu: "200m"
          requests:
            memory: "10Mi"
            cpu: "100m"        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          failureThreshold: 1
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /readz
            port: 80
          failureThreshold: 30
          periodSeconds: 5
          initialDelaySeconds: 
